server:
  port: 8999
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-2zea089gtq9s1hu69.mysql.rds.aliyuncs.com:3306/stock?multiStatement=true&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&serverTimezone=CTT
    username: root
    password: Xkw100*-
    #password: lmx@123456
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 3000000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: true
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙，加了wall 无法批量更新
    filters: stat,log4j
    logSlowSql: true
  resources:
    staticLocations:classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  redis:
    host: 39.97.172.32
    port: 6379
    password: Xkw100*-
    jedis:
      pool:
        max-active: 20
        min-idle: 0
    timeout: 10000s
    database: 1
  server:
    url: http://101.132.137.156:8999
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html
logging:
  config: classpath:logback.xml
mybatis:
  mapper-locations: classpath:mybatis-config.xml
  type-aliases-package: com.app.stock.mapper
image:
  path:
    avatar: /data/image/avatar/
    advertise: /data/image/advertise/
    subject: /data/image/subject/
    vedio: /data/video/subject/
showapi:
  key: 8e5cc51d121d4ca4ad0cbb496b42a01a
  appId: 88931
  news:
    url: http://route.showapi.com/109-35
    channelId: 5572a108b3cdc86cf39001d0
  stock:
    url: http://route.showapi.com/131-46
  stockData:
    url: http://route.showapi.com/1529-4
